### ISSUE TITLE
请问现在已经可以用来搭建论坛了吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [leiphp/go-bbs#1]

**Comment by leiphp** [comment]
还不行，只写了个首页。详细的跟这个差不多bbs.100txy.com

**Comment by Yakumo-Yukari** [comment]
> 还不行，只写了个首页。详细的跟这个差不多bbs.100txy.com

哦，你这个UI是用那个PHP轻社区那个吗？你可以看看这个  https://pmj136.top/

这个UI改的比较不错
